### ISSUE TITLE
OS X - crust_peer - thread '<unnamed>' panicked at 'Http11Message lost its underlying stream somehow

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/crust#262]
Panic when running crust_peer example on OS X

```
CI-OSX-64:SAFENetwork_examples ci-mac$ ./crust_peer 
thread '<unnamed>' panicked at 'Http11Message lost its underlying stream somehow', /Users/jenkins/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.10/src/http/h1.rs:270
Listening for new connections on Tcp(V4(192.168.1.69:55130)), Tcp(V4(192.168.0.20:55130)), Didn't bootstrap to an existing network - this may be the first node of a new network.
^C
```
With RUST_LOG=debug on
```
CI-OSX-64:SAFENetwork_examples ci-mac$ RUST_LOG=debug ./crust_peer
DEBUG:hyper::net: http scheme
DEBUG:hyper::net: http scheme
DEBUG:hyper::http::h1: request line: Get "/uyd4tz2eg1i/IGD/upnp/IGD.xml" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: 192.168.1.254:8000, }
DEBUG:hyper::http::h1: request line: Get "/RootDevice.xml" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: 192.168.0.1, }
DEBUG:hyper::client::response: version=Http10, status=Ok
DEBUG:hyper::client::response: headers=Headers { Cache-Control: no-cache, Content-Type: text/xml, Expires: -1, }
DEBUG:hyper::client::response: version=Http11, status=Ok
DEBUG:hyper::client::response: headers=Headers { Content-Length: 2892, Content-type: text/xml, Connection: close, Expires: Thu, 3 Oct 1968 12:00:00 GMT, Pragma: no-cache, }
DEBUG:hyper::net: http scheme
DEBUG:hyper::http::h1: request line: Post "/WANIPConnection" Http11
DEBUG:hyper::http::h1: headers=Headers { SOAPAction: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping", Host: 192.168.0.1, Content-Length: 792, }
thread '<unnamed>' panicked at 'Http11Message lost its underlying stream somehow', /Users/jenkins/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.10/src/http/h1.rs:270
Listening for new connections on Tcp(V4(192.168.1.69:55135)), Tcp(V4(192.168.0.20:55135)), Didn't bootstrap to an existing network - this may be the first node of a new network.```

**Comment by vinipsmaker** [comment]
Related to UPnP. Probably worth checking: https://github.com/SBSTP/rust-igd/issues/4

**Comment by vinipsmaker** [comment]
Can you check if this error still happens?

**Comment by vinipsmaker** [comment]
Maybe we should update [`rust-igd` to 0.4.0](https://github.com/sbstp/rust-igd/releases/tag/v0.4.0) nevertheless, which has some changes from @canndrew and changes a lot of the code.

**Comment by vinipsmaker** [comment]
I opened a new issue to track the task: https://github.com/maidsafe/crust/issues/464

Gonna close this issue.
