### ISSUE TITLE
Crust 0.3.1 hits assert on bootstrapping network (while sending messages)

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/crust#334]
```thread 'Service::run loop' panicked at 'explicit panic', /home/bbollen/.multirust/toolchains/nightly/cargo/git/checkouts/crust-c8dfa13e39bc3355/master/src/service.rs:265
thread '<unnamed>' panicked at 'assertion failed: sender.send(Box::new(cmd)).is_ok()', /home/bbollen/.multirust/toolchains/nightly/cargo/git/checkouts/crust-c8dfa13e39bc3355/master/src/service.rs:372```

context: routing network bootstrap; the sending of messages causes all receiving nodes to simultaneously panic, after an arbitrary number of previously successful connections

```DEBUG:routing::routing_node: Sending InternalRequest(CacheNetworkName(PublicId(name:31d23e..d58d83), SignedToken)) to 8 target connection(s)
DEBUG:routing::routing_node: Queuing message for processing ourselves
DEBUG:routing::routing_node: Accumulator threshold is at 5
DEBUG:routing::routing_node: Adding message from 8c48fe..39de0d to accumulator
DEBUG:routing::routing_node: Sending InternalRequest(Connect(ConnectRequest { local_endpoints: [Tcp(V4(127.0.0.1:35181))], external_endpoints: [], requester_fob: PublicId(name:31d23e..d58d83) })) to 8 target connection(s)
DEBUG:routing::routing_node: Queuing message for processing ourselves
thread 'Service::run loop' panicked at 'explicit panic', /home/bbollen/.multirust/toolchains/nightly/cargo/git/checkouts/crust-c8dfa13e39bc3355/master/src/service.rs:265
DEBUG:routing::routing_node: message from unknown connection
DEBUG:routing::routing_node: message from unknown connection
DEBUG:routing::routing_node: Sending InternalRequest(Connect(ConnectRequest { local_endpoints: [Tcp(V4(127.0.0.1:35181))], external_endpoints: [], requester_fob: PublicId(name:31d23e..d58d83) })) to 8 target connection(s)
thread '<unnamed>' panicked at 'assertion failed: sender.send(Box::new(cmd)).is_ok()', /home/bbollen/.multirust/toolchains/nightly/cargo/git/checkouts/crust-c8dfa13e39bc3355/master/src/service.rs:372```

**Comment by benjaminbollen** [comment]
this failure to send, either has always been there and was simply hidden in the previous crust, or some internal crust (dependency) is causing the failure.

**Comment by benjaminbollen** [comment]
Can we put a crust `error!()` log on those places.  If routing indeed is sending on closed connections, we'd want to amend routing too - to the extend possible
