### ISSUE TITLE
Unable to connect to more than ~48 peers when running crust_peer example on OS X

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#382]
Running crust_peer on OS X 10.11 with a crust_peer.crust.config file containing endpoints of 64 droplets all running crust_peer yields the following error:

```
Connected to peer at Tcp(V4(46.101.16.32:5483))
Connected node count: 48
    [0] Connection(Tcp V4(192.168.0.8:55073) -> V4(46.101.19.43:5483))
    [1] Connection(Tcp V4(192.168.0.8:55074) -> V4(178.62.53.115:5483))
    [2] Connection(Tcp V4(192.168.0.8:55075) -> V4(178.62.78.84:5483))
    [3] Connection(Tcp V4(192.168.0.8:55076) -> V4(178.62.117.237:5483))
    [4] Connection(Tcp V4(192.168.0.8:55077) -> V4(178.62.35.131:5483))
    [5] Connection(Tcp V4(192.168.0.8:55078) -> V4(178.62.105.169:5483))
    [6] Connection(Tcp V4(192.168.0.8:55079) -> V4(178.62.79.88:5483))
    [7] Connection(Tcp V4(192.168.0.8:55080) -> V4(178.62.86.147:5483))
    [8] Connection(Tcp V4(192.168.0.8:55081) -> V4(46.101.63.251:5483))
    [9] Connection(Tcp V4(192.168.0.8:55082) -> V4(46.101.44.47:5483))
    [10] Connection(Tcp V4(192.168.0.8:55083) -> V4(46.101.48.231:5483))
    [11] Connection(Tcp V4(192.168.0.8:55084) -> V4(178.62.31.84:5483))
    [12] Connection(Tcp V4(192.168.0.8:55085) -> V4(46.101.3.80:5483))
    [13] Connection(Tcp V4(192.168.0.8:55086) -> V4(46.101.24.178:5483))
    [14] Connection(Tcp V4(192.168.0.8:55087) -> V4(46.101.63.233:5483))
    [15] Connection(Tcp V4(192.168.0.8:55088) -> V4(46.101.36.106:5483))
    [16] Connection(Tcp V4(192.168.0.8:55089) -> V4(178.62.6.242:5483))
    [17] Connection(Tcp V4(192.168.0.8:55090) -> V4(178.62.4.97:5483))
    [18] Connection(Tcp V4(192.168.0.8:55091) -> V4(46.101.16.205:5483))
    [19] Connection(Tcp V4(192.168.0.8:55092) -> V4(178.62.31.50:5483))
    [20] Connection(Tcp V4(192.168.0.8:55093) -> V4(178.62.99.234:5483))
    [21] Connection(Tcp V4(192.168.0.8:55094) -> V4(178.62.44.183:5483))
    [22] Connection(Tcp V4(192.168.0.8:55095) -> V4(178.62.12.4:5483))
    [23] Connection(Tcp V4(192.168.0.8:55096) -> V4(46.101.15.20:5483))
    [24] Connection(Tcp V4(192.168.0.8:55097) -> V4(46.101.26.5:5483))
    [25] Connection(Tcp V4(192.168.0.8:55098) -> V4(46.101.2.95:5483))
    [26] Connection(Tcp V4(192.168.0.8:55099) -> V4(46.101.12.46:5483))
    [27] Connection(Tcp V4(192.168.0.8:55100) -> V4(178.62.25.82:5483))
    [28] Connection(Tcp V4(192.168.0.8:55101) -> V4(46.101.2.234:5483))
    [29] Connection(Tcp V4(192.168.0.8:55102) -> V4(178.62.113.245:5483))
    [30] Connection(Tcp V4(192.168.0.8:55103) -> V4(178.62.17.130:5483))
    [31] Connection(Tcp V4(192.168.0.8:55105) -> V4(46.101.19.41:5483))
    [32] Connection(Tcp V4(192.168.0.8:55107) -> V4(178.62.40.183:5483))
    [33] Connection(Tcp V4(192.168.0.8:55109) -> V4(178.62.54.176:5483))
    [34] Connection(Tcp V4(192.168.0.8:55111) -> V4(46.101.31.246:5483))
    [35] Connection(Tcp V4(192.168.0.8:55113) -> V4(178.62.22.37:5483))
    [36] Connection(Tcp V4(192.168.0.8:55115) -> V4(178.62.10.9:5483))
    [37] Connection(Tcp V4(192.168.0.8:55117) -> V4(46.101.19.167:5483))
    [38] Connection(Tcp V4(192.168.0.8:55119) -> V4(178.62.110.232:5483))
    [39] Connection(Tcp V4(192.168.0.8:55121) -> V4(178.62.62.6:5483))
    [40] Connection(Tcp V4(192.168.0.8:55123) -> V4(46.101.22.140:5483))
    [41] Connection(Tcp V4(192.168.0.8:55125) -> V4(46.101.4.171:5483))
    [42] Connection(Tcp V4(192.168.0.8:55127) -> V4(178.62.65.79:5483))
    [43] Connection(Tcp V4(192.168.0.8:55129) -> V4(178.62.27.190:5483))
    [44] Connection(Tcp V4(192.168.0.8:55131) -> V4(178.62.8.245:5483))
    [45] Connection(Tcp V4(192.168.0.8:55133) -> V4(46.101.4.199:5483))
    [46] Connection(Tcp V4(192.168.0.8:55135) -> V4(46.101.45.41:5483))
    [47] Connection(Tcp V4(192.168.0.8:55137) -> V4(46.101.16.32:5483))
Udp socket count: 0

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', ../src/libcore/result.rs:736
stack backtrace:
   1:        0x10fd16a58 - sys::backtrace::tracing::imp::write::h7ae3fb30e3d277c5yZs
   2:        0x10fd1852f - panicking::log_panic::_<closure>::closure.38948
   3:        0x10fd17fd9 - panicking::log_panic::h2463655e45799b7bJOw
   4:        0x10fd055c6 - sys_common::unwind::begin_unwind_inner::h1e0a110fc6710e2561r
   5:        0x10fd059ae - sys_common::unwind::begin_unwind_fmt::hde354428d7b06c2ec1r
   6:        0x10fd160e7 - rust_begin_unwind
   7:        0x10fd39770 - panicking::panic_fmt::hb9f15bd9c64410c4kMK
   8:        0x10fba0905 - result::_<impl>::unwrap::unwrap::h4507272197241775999
   9:        0x10fc2c51c - asynchronous::_<impl>::process_parallel::_<closure>::closure.23051
  10:        0x10fc29a76 - boxed::_<impl>::call_box::call_box::h6204665560060982022
  11:        0x10fb79572 - sys_common::unwind::try::try_fn::try_fn::h8694432854930233049
  12:        0x10fd15f28 - __rust_try
  13:        0x10fd133ee - sys_common::unwind::try::inner_try::h01d33f1b9d169bb6EYr
  14:        0x10fb79717 - boxed::_<impl>::call_box::call_box::h7455542894398686131
  15:        0x10fd178fd - sys::thread::_<impl>::new::thread_start::h68e6f797e733185eZlw
  16:     0x7fff9c8219b0 - _pthread_body
  17:     0x7fff9c82192d - _pthread_start
thread 'State::bootstrap_off_list' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:736
stack backtrace:
   1:        0x10fd16a58 - sys::backtrace::tracing::imp::write::h7ae3fb30e3d277c5yZs
   2:        0x10fd1852f - panicking::log_panic::_<closure>::closure.38948
   3:        0x10fd17fd9 - panicking::log_panic::h2463655e45799b7bJOw
   4:        0x10fd055c6 - sys_common::unwind::begin_unwind_inner::h1e0a110fc6710e2561r
   5:        0x10fd059ae - sys_common::unwind::begin_unwind_fmt::hde354428d7b06c2ec1r
   6:        0x10fd160e7 - rust_begin_unwind
   7:        0x10fd39770 - panicking::panic_fmt::hb9f15bd9c64410c4kMK
   8:        0x10fc12846 - state::_<impl>::bootstrap_off_list::_<closure>::closure.22314
   9:        0x10fc0d896 - boxed::_<impl>::call_box::call_box::h5903651598099049785
  10:        0x10fb79572 - sys_common::unwind::try::try_fn::try_fn::h8694432854930233049
  11:        0x10fd15f28 - __rust_try
  12:        0x10fd133ee - sys_common::unwind::try::inner_try::h01d33f1b9d169bb6EYr
  13:        0x10fb79717 - boxed::_<impl>::call_box::call_box::h7455542894398686131
  14:        0x10fd178fd - sys::thread::_<impl>::new::thread_start::h68e6f797e733185eZlw
  15:     0x7fff9c8219b0 - _pthread_body
  16:     0x7fff9c82192d - _pthread_start
```

The example continues to run, and is usable (i.e. sending/receiving messages from connected peers succeeds), but the bootstrap event is not reported.

Further connections cannot be made using the `connect` option (although again, the tool continues to run after the panic).  These yield errors like:

```
> connect Tcp(46.101.2.234:5483)
Connecting to Tcp(V4(46.101.2.234:5483))
> thread 'Service::connect' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', ../src/libcore/result.rs:736
stack backtrace:
   1:        0x10f687a58 - sys::backtrace::tracing::imp::write::h7ae3fb30e3d277c5yZs
   2:        0x10f68952f - panicking::log_panic::_<closure>::closure.38948
   3:        0x10f688fd9 - panicking::log_panic::h2463655e45799b7bJOw
   4:        0x10f6765c6 - sys_common::unwind::begin_unwind_inner::h1e0a110fc6710e2561r
   5:        0x10f6769ae - sys_common::unwind::begin_unwind_fmt::hde354428d7b06c2ec1r
   6:        0x10f6870e7 - rust_begin_unwind
   7:        0x10f6aa770 - panicking::panic_fmt::hb9f15bd9c64410c4kMK
   8:        0x10f53a659 - tcp_connections::upgrade_tcp::h47a09dd6721c4412XQc
   9:        0x10f50509f - state::_<impl>::connect::h36b16da45e55b841Fce
  10:        0x10f503c73 - boxed::_<impl>::call_box::call_box::h16820619058248378462
  11:        0x10f4ea572 - sys_common::unwind::try::try_fn::try_fn::h8694432854930233049
  12:        0x10f686f28 - __rust_try
  13:        0x10f6843ee - sys_common::unwind::try::inner_try::h01d33f1b9d169bb6EYr
  14:        0x10f4ea717 - boxed::_<impl>::call_box::call_box::h7455542894398686131
  15:        0x10f6888fd - sys::thread::_<impl>::new::thread_start::h68e6f797e733185eZlw
  16:     0x7fff9c8219b0 - _pthread_body
  17:     0x7fff9c82192d - _pthread_start
```

This is repeatable - every attempt so far has had similar results with only the actual number of successful connections varying slightly.

Running `ulimit -a` yields:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 512
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

**Comment by inetic** [comment]
Should be fixed by [this PR](https://github.com/maidsafe/crust/pull/390)
